# Generated by Django 4.1 on 2024-08-26 07:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("post", models.TextField()),
                ("body", models.TextField()),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
                ("rating", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Movie",
            fields=[
                ("id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=200)),
                ("original_title", models.CharField(max_length=200)),
                ("overview", models.TextField()),
                ("vote_average", models.FloatField()),
                ("poster_path", models.CharField(max_length=255)),
                ("runtime", models.IntegerField()),
                ("status", models.CharField(max_length=50)),
                ("tagline", models.CharField(blank=True, max_length=255, null=True)),
                ("genres", models.CharField(max_length=255)),
                ("keywords", models.CharField(max_length=255)),
                ("directors", models.CharField(max_length=255)),
                ("actors", models.CharField(max_length=255)),
            ],
        ),
    ]
