# Generated by Django 4.1 on 2024-08-27 07:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="user",
            field=models.TextField(
                default=datetime.datetime(
                    2024, 8, 27, 7, 56, 7, 462787, tzinfo=datetime.timezone.utc
                )
            ),
            preserve_default=False,
        ),
    ]
